Стилизация страницы каталога
htmlacademy-adaptive/1662671-sedona-22 pull request #7
Opened 2021-04-20 20:41 UTC by Sunnyside92

2021-04-22 07:51 UTC, craz3r requested changes

2021-04-22 07:51 UTC, craz3r commented on source/less/blocks/video.less
> +.tools-wrapper {
что делает класс tools-wrapper в бэм файле video?

2021-04-22 07:51 UTC, craz3r commented on source/less/blocks/video.less
> +.tools {
см комментарий выше

2021-04-25 15:14 UTC, Sunnyside92 commented on source/less/blocks/video.less
> +.tools-wrapper {
Поправила

2021-04-26 05:54 UTC, merged